[package]
name = "json-parser"
version = "0.1.0"
authors = ["Kieran <kraine93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
escape8259 = "0.5.0"
nom = "6.1.2"
thiserror = "1.0.24"
